---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "${SERVICE_NAME}"
  spec:
    ports:
    - name: "http"
      port: ${INTERNAL_INGRESS_PORT}
      targetPort: ${INTERNAL_PORT}
    selector:
      deployment: "${SERVICE_NAME}"
    type: "ClusterIP"
- apiVersion: "apps/v1"
  kind: "Deployment"
  metadata:
    name: "${SERVICE_NAME}"
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: "${SERVICE_NAME}"
    template:
      metadata:
        labels:
          deployment: "${SERVICE_NAME}"
      spec:
        containers:
        - image: "${IMAGE}"
          args: [${ARGS}]
          imagePullPolicy: "IfNotPresent"
          name: "${SERVICE_NAME}"
          ports:
          - containerPort: ${INTERNAL_PORT}
            name: "http"
            protocol: "TCP"
    triggers:
    - type: "ConfigChange"
      