name: "Release version check"
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - .github/project.yml
jobs:
  check-release-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check release version
        run: |
          cd .github
          bash check-release-version.sh
