name: Check release version
on:
  push:
    paths:
      - .github/project.yml
jobs:
  check-release-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check release version
        run: |
          release=$(curl -sSL "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest" | jq -r .tag_name)
          release_subversion=$(echo "$release" | cut -d"." -f3,3)
          release_stage_number=$(echo "$release" | cut -d"." -f4,4 | grep -o '[0-9]'  || true)

          next_version=$(grep -E 'current-version:\s*' .github/project.yml | awk '{print $2}')
          next_version_subversion=$(echo "$next_version" | cut -d"." -f3,3)
          next_version_stage_number=$(echo "$next_version" | cut -d"." -f4,4 | grep -o '[0-9]' || true)

          if ! [[ $release =~ .*Final$ ]]; then
            if [[ $next_version_subversion > $release_subversion ]]; then
              echo "Error: you are bumping the FW sub version when the previous release was not Final"
              exit 1;
            fi
            if [[ $next_version_stage_number != $(("$release_stage_number" + 1)) ]]; then
              echo "Error: release stage numbers should go in sequence"
              exit 1;
            fi
          else
            if [[ $(("$release_subversion" + 1)) != $next_version_subversion || ($next_version_stage_number != 1) ]]; then
                echo "Error: release sub versions should go in sequence"
                exit 1;
              fi
          fi